import React from 'react';
import { motion } from 'motion/react';
import { Users, Calendar, MapPin, DollarSign, ShieldCheck, Zap, Activity, ChevronRight } from 'lucide-react';

interface PlanOverviewProps {
  steps: any[];
  currentStepIndex: number;
  isProcessing: boolean;
  customerData: any;
  eventData: any;
  pricingData: any;
  monitoringData: any;
  reportView: string;
}

export function PlanOverview({
  steps,
  currentStepIndex,
  isProcessing,
  customerData,
  eventData,
  pricingData,
  monitoringData,
  reportView
}: PlanOverviewProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="mb-8 rounded-[2.5rem] border border-slate-200/60 bg-white/80 p-8 shadow-2xl shadow-slate-200/50 backdrop-blur-xl"
    >
      <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-emerald-600 border border-emerald-100/50">
            <Zap className="h-3 w-3 fill-emerald-600" />
            AI Orchestration Active
          </div>
          <h2 className="text-3xl font-black tracking-tight text-slate-900 lg:text-4xl">
            Event Blueprint <span className="text-slate-400 font-medium font-serif italic">v1.0</span>
          </h2>
          <p className="max-w-2xl text-sm font-medium leading-relaxed text-slate-500">
            A high-fidelity catering strategy generated by <span className="text-emerald-600 font-bold">11 specialized agents</span>.
          </p>
        </div>
        
        <div className="flex items-center gap-4 bg-slate-900 rounded-[2rem] p-2 pl-6 shadow-xl">
          <div className="text-left">
            <p className="text-[9px] font-black uppercase tracking-[0.2em] text-slate-400">Current Phase</p>
            <p className="text-xs font-black text-white uppercase tracking-tighter">
              {reportView === 'menu' ? 'Menu Strategy' : reportView === 'logistics' ? 'Ops & Logistics' : reportView === 'finance' ? 'Finance' : 'Full Workflow'}
            </p>
          </div>
          <div className="h-10 w-10 rounded-full bg-emerald-500 flex items-center justify-center shadow-lg shadow-emerald-500/40">
            <Activity className="h-5 w-5 text-white animate-pulse" />
          </div>
        </div>
      </div>

      <div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-5">
        <StatCard icon={<Users />} label="Servings" value={customerData.guests || eventData.guest_count || '--'} color="emerald" />
        <StatCard icon={<Calendar />} label="Event Date" value={customerData.date || eventData.event_date || '--'} color="blue" />
        <StatCard icon={<MapPin />} label="Venue Location" value={customerData.location || eventData.event_location || '--'} color="amber" />
        <StatCard icon={<DollarSign />} label="Target Quote" value={pricingData.optimized_quote || '--'} color="rose" />
        <StatCard icon={<ShieldCheck />} label="Execution Readiness" value={monitoringData.execution_readiness ? `${monitoringData.execution_readiness}%` : isProcessing ? 'Syncing...' : '--'} color="indigo" />
      </div>

      <div className="mt-10 relative">
        <div className="absolute inset-0 flex items-center" aria-hidden="true">
          <div className="w-full border-t border-slate-100"></div>
        </div>
        <div className="relative flex justify-center">
          <span className="bg-white px-4 text-[10px] font-black uppercase tracking-[0.3em] text-slate-400">Pipeline Status</span>
        </div>
      </div>

      <div className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-5">
        {['Brief', 'Menu', 'Procurement', 'Logistics', 'Finance'].map((item, index) => {
          const isDone = index <= (monitoringData.execution_readiness ? 4 : steps.length > 5 ? 2 : 1);
          return (
            <motion.div 
              key={item}
              whileHover={{ scale: 1.02 }}
              className={`relative flex items-center justify-between rounded-2xl border px-5 py-4 transition-all ${
                isDone 
                ? 'border-emerald-100 bg-emerald-50/50 text-emerald-800 shadow-sm' 
                : 'border-slate-100 bg-slate-50/50 text-slate-400 opacity-60'
              }`}
            >
              <span className="text-[11px] font-black uppercase tracking-widest">{item}</span>
              {isDone && <CheckCircle2 className="h-4 w-4 text-emerald-600" />}
            </motion.div>
          );
        })}
      </div>

      {monitoringData.execution_readiness && (
        <motion.div
          initial={{ opacity: 0, scale: 0.98, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="mt-10 p-8 rounded-[3rem] bg-slate-950 text-white shadow-2xl relative overflow-hidden group"
        >
          {/* Decorative Elements */}
          <div className="absolute top-0 right-0 w-96 h-96 bg-emerald-500/20 blur-[100px] rounded-full -translate-y-1/2 translate-x-1/2 group-hover:bg-emerald-500/30 transition-colors duration-700"></div>
          <div className="absolute bottom-0 left-0 w-64 h-64 bg-indigo-500/10 blur-[80px] rounded-full translate-y-1/2 -translate-x-1/2"></div>
          
          <div className="relative z-10">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl font-black tracking-tighter uppercase font-mono italic flex items-center gap-3">
                <div className="w-8 h-8 rounded-lg bg-emerald-500 flex items-center justify-center not-italic shadow-lg shadow-emerald-500/20">
                  <Zap className="w-4 h-4 text-white fill-white" />
                </div>
                Optimized Catering Plan
              </h2>
              <div className="px-4 py-1.5 rounded-full bg-white/10 border border-white/10 backdrop-blur-md text-[10px] font-black uppercase tracking-widest">
                Confidential Report
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 py-8 border-y border-white/5">
              <SummaryItem label="ALLOCATED_BUDGET" value={customerData.budget || eventData.budget || '--'} highlight />
              <SummaryItem label="IDENTIFIED_GUESTS" value={customerData.guests || eventData.guest_count || '--'} />
              <SummaryItem label="PLAN_VIABILITY" value={`${monitoringData.execution_readiness}%`} highlight />
            </div>

            <div className="mt-8 flex flex-col md:flex-row md:items-center gap-6">
              <div className="flex-1 p-5 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm">
                <p className="text-[12px] font-medium font-mono text-slate-300 leading-relaxed italic">
                  "{monitoringData.final_summary || 'Synchronizing final data from specialist agents...'}"
                </p>
              </div>
              <button className="h-fit bg-emerald-500 hover:bg-emerald-400 text-slate-950 px-8 py-4 rounded-2xl font-black uppercase tracking-[0.2em] text-[10px] transition-all flex items-center gap-3 group shadow-xl shadow-emerald-500/20 active:scale-95">
                Download PDF
                <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </button>
            </div>
          </div>
        </motion.div>
      )}
    </motion.div>
  );
}

function StatCard({ icon, label, value, color }: { icon: React.ReactNode, label: string, value: string, color: string }) {
  const colorStyles: any = {
    emerald: 'text-emerald-600 bg-emerald-50 border-emerald-100/50',
    blue: 'text-blue-600 bg-blue-50 border-blue-100/50',
    amber: 'text-amber-600 bg-amber-50 border-amber-100/50',
    rose: 'text-rose-600 bg-rose-50 border-rose-100/50',
    indigo: 'text-indigo-600 bg-indigo-50 border-indigo-100/50'
  };

  return (
    <motion.div 
      whileHover={{ y: -5 }}
      className={`rounded-[2rem] border p-6 transition-all hover:shadow-xl hover:shadow-slate-100 bg-white ${colorStyles[color]}`}
    >
      <div className="flex items-center gap-3 mb-4 opacity-80">
        <div className="p-2 rounded-xl bg-white shadow-sm border-inherit border">
          {React.cloneElement(icon as React.ReactElement, { className: 'w-4 h-4' })}
        </div>
        <span className="text-[9px] font-black uppercase tracking-widest text-slate-400">{label}</span>
      </div>
      <p className="text-xl font-black text-slate-900 tracking-tight truncate">{value}</p>
    </motion.div>
  );
}

function SummaryItem({ label, value, highlight = false }: { label: string, value: string, highlight?: boolean }) {
  return (
    <div className="space-y-1">
      <span className="text-[9px] uppercase font-black text-slate-500 tracking-[0.2em] block">{label}</span>
      <p className={`text-3xl font-black font-mono tracking-tighter ${highlight ? 'text-emerald-400' : 'text-white'}`}>
        {value}
      </p>
    </div>
  );
}

function CheckCircle2({ className }: { className?: string }) {
  return (
    <svg 
      className={className} 
      xmlns="http://www.w3.org/2000/svg" 
      width="24" 
      height="24" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="3" 
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  );
}

